:- module(concepts,[]).

comment(absolutePin/4,'A pin against the king is called absolute since the pinned piece cannot legally move out of the line of attack (as moving it would expose the king to check).[1] Cf. relative pin.').
absolutePin(on(piece(Color1,Type1),square(X1,Y1)),on(piece(Color2,Type2),square(X2,Y2)),on(piece(Color2,king),square(X3,Y3)),Pos) :-
	pin(on(piece(Color1,Type1),square(X1,Y1)),on(piece(Color2,Type2),square(X2,Y2)),on(piece(Color2,king),square(X3,Y3)),Pos).

active().
adjournment().
adjudication().
adjust().

comment(advancedPawn/2,'A pawn that is on the opponent''s side of the board (the fifth rank or higher). An advanced pawn may be weak if it is overextended, lacking support and difficult to defend, or strong if it cramps the enemy by limiting mobility. An advanced passed pawn that threatens to promote can be especially strong.[6]').
advancedPawn(on(piece(Color,pawn),square(_X1,Y1)),Pos) :-
	position:in(on(piece(Color,pawn),square(_X1,Y1)),Pos),
	(   Color = white -> Y1 > 4 ;
	    (	Color = black -> Y1 < 5 ; fail)).

advantage().
alekhinesGun().
algebraicNotation().
amateur().
analysis().
annotation().
announcedMate().
antipositional().
antiSicilian().
arabianMate().
arbiter().
armageddonGame().
artificialCastling().
attack().
attraction().
automaton().
backRank().
backRankMate().
backRankWeakness().
backwardPawn().
badBishop().
bareKing().
basqueChess().
battery().
bCF().
bCM().
bCO().
bestPlay().
bigPawn().
bind().
bishop().
bishopPair().
bishopPawn().
bishopsOnOppositeColors().
black().
blindChess().
blindfoldChess().
blindPigs().
blitzChess().
blockade().
blockedPosition().
blunder().
board().
boardOne().
bodensMate().
bookDraw().
bookMove().
bookWin().
break().
breakthrough().
brevity().
brilliancy().
brilliancyPrize().
bronsteinDelay().
bughouseChess().
buildingABridge().
bulletChess().
bust().
bye().
caïssa().
calculate().
candidateMove().
candidatesMatch().
candidatesTournament().
canOpener().
cappedPiece().
capture().
castling().
castlingIntoIt().
castlingLong().
castlingShort().
casualGame().
categoryOfATournament().
center().
centerFile().
centerPawn().
centralFile().
centralization().
centralPawn().
cheapo().
check().
checkmate().
chessBlindness().
chessboard().
chessClock().
chessmen().
chessNotation().
chessOpening().
chessProblem().
chessSet().
chessVariant().
chess960().
chopWood().
classical().
classicalBishopSacrifice().
clearance().
clockMove().
clockTime().
closedFile().
closedGame().
closedGame().
closedTournament().
coffeehouse().
color().
combination().
compensation().
computerMove().
confirmationBias().
connectedPassedPawns().
connectedPawns().
connectedRooks().
consolidation().
continuation().
control().
controlOfTheCenter().
cook().
correspondenceChess().
correspondingSquares().
counterattack().
countergambit().
counterplay().
countryMove().
cover().
cramped().
criticalPosition().
criticalSquare().
crossCheck().
crosstable().
crush().
darkSquareBishop().
darkSquares().
deadDraw().
decoy().
defense().
deflect().
demonstrationBoard().
descriptiveNotation().
desperado().
development().
diagonal().
discoveredAttack().
discoveredCheck().
domination().
doubleAttack().
doubleCheck().
doubledPawns().
doubledRooks().
draw().
drawByAgreement().
drawDeath().
drawingLine().
drawingWeapon().
drawish().
drawOdds().
drawOffer().
dynamism().
eat().
eCF().
eCO().
edge().
eloRatingSystem().
endgame().
endgameTablebase().
enPassant().
enPrise().
epauletteMate().
ePD().
equalize().
escapeSquare().
evaluation().
exchange().
exchangeVariation().
exhibition().
expandedCenter().
exposedKing().
extendedPositionDescription().
familyFork().
fAN().
fastChess().
fEN().
fGM().
fianchetto().
fICGSGrandmaster().
fIDE().
fIDEMaster().
fiftyMoveRule().
file().
fingerfehler().
firstBoard().
firstMoveAdvantage().
firstPlayer().
firstRank().
fischerDelay().
fischerRandomChess().
fiveMinuteChess().
flag().
flank().
flankOpening().
flightSquare().
fM().
foolsMate().
forcedMate().
forcedMove().
forcedWin().
forcingMove().
forfeit().
fork().
forsythEdwardsNotation().
fortress().
friendlyGame().
gambit().
gameClock().
gameScore().
gardez().
gM().
god().
goodBishop().
grandmaster().
grandmasterDraw().
greekGiftSacrifice().
halfOpenFile().
handicap().
hanging().
hangingPawns().
harry().
hauptturnier().
heavyPiece().
hole().
homeRank().
horizontalLine().
horwitzBishops().
humanMove().
huttonPairing().
hypermodernism().
iCCA().
iCCF().
iCS().
iGM().
illegalMove().
illegalPosition().
iM().
imbalance().
inaccuracy().
inactive().
increment().
indianBishop().
indianDefense().
initiative().
innovation().
insufficientMaterial().
interference().
intermediateMove().
intermezzo().
internationalArbiter().
internationalCorrespondenceChessFederation().
internationalGrandmaster().
internationalMaster().
internationalWomanMaster().
internetChessServer().
interpose().
interzonalTournament().
intuition().
iQP().
irregularOpening().
isolani().
isolatedPawn().
italianBishop().
jAdoube().
keySquare().
kGA().
kGD().
kIA().
kibitz().
kick().
kID().
king().
kingBishop().
kingHunt().
kingKnight().
kingPawn().
kingPawnOpening().
kingRook().
kingside().
kingWalk().
knight().
knightPawn().
knightsTour().
knockoutTournament().
kotovSyndrome().
kriegspiel().
kt().
lawsOfChess().
lightningChess().
lightSquareBishop().
lightSquares().
line().
linePiece().
liquidation().
longDiagonal().
longRangePiece().
loosePiece().
loosePosition().
losingATempo().
loss().
lucenaPosition().
luft().
mainLine().
majority().
majorPiece().
man().
maróczyBind().
master().
match().
mate().
material().
materialism().
matingAttack().
matingNet().
mCO().
middlegame().
miniature().
minorExchange().
minorityAttack().
minorPiece().
mobilePawnCenter().
mobility().
mouseSlip().
move().
moveOrder().
mysteriousRookMove().
nCO().
nN().
norm().
notation().
novelty().
occupation().
octopus().
odds().
offhandGame().
olympiad().
o_o().
o_o_o().
openFile().
openGame().
openGame().
opening().
openingInnovation().
openingPreparation().
openingRepertoire().
openingSystem().
openLines().
openTournament().
oppositeColoredBishops().
opposition().
optimalPlay().
oTB().
outpost().
outsidePassedPawn().
overextended().
overloaded().
overprotection().
overTheBoard().
overworked().
pairing().
passedPawn().
passer().
passive().
passiveSacrifice().
patternRecognition().
patzer().
pawn().
pawnAndMove().
pawnBreak().
pawnCenter().
pawnChain().
pawnIsland().
pawnMajority().
pawnRace().
pawnRoller().
pawnSkeleton().
pawnStorm().
pawnStructure().
pCA().
performanceRating().
perpetualCheck().
pGN().
philidorPosition().
piece().

% When a piece is attacked but cannot legally move, because doing so would expose the player's own king to the attack; or when a piece is attacked and can legally move out of the line of attack, but such a move would expose a more valuable piece (or an unprotected piece) to capture.[227] See absolute pin and relative pin, respectively.
pin(on(piece(Color1,Type1),square(X1,Y1)),on(piece(Color2,Type2),square(X2,Y2)),on(piece(Color2,Type3),square(X3,Y3)),Pos) :-
	board:attack(on(piece(Color1,Type1),square(X1,Y1)),on(piece(Color2,Type2),square(X2,Y2)),Pos),
	board:colinear(square(X1,Y1),square(X2,Y2),Line),
	board:colinear(square(X1,Y1),square(X3,Y3),Line),
	position:in(on(piece(Color2,Type3),square(X3,Y3)),Pos),
	member(Type1,[bishop,rook,queen]),
	board:hasValue(Type2,Value2),
	board:hasValue(Type3,Value3),
	Value3 > Value2,
	board:lies_between(square(X1,Y1),square(X2,Y2),square(X3,Y3)),
	findall(square(X4,Y4),
		(   board:lies_between(square(X2,Y2),square(X4,Y4),square(X3,Y3)),
		    %% view([square(X2,Y2,X4,Y4,X3,Y3)]),
		    position:in(on(piece(_Color,_Type),square(X4,Y4)),Pos)),
		Occupied),
	length(Occupied,0).

plan().
playable().
playByHand().
ply().
poisonedPawn().
poisonedPawnVariation().
portableGameNotation().
positionalPlay().
positionalPlayer().
positionalSacrifice().
postMortem().
preparation().
preparedVariation().
principleOfTwoWeaknesses().
priyome().
problemLike().
promotion().
prophylaxis().
protectedPassedPawn().
pseudoSacrifice().
push().
qGA().
qGD().
qID().
quad().
queen().
queenBishop().
queening().
queenKnight().
queenPawn().
queenPawnOpening().
queenRook().
queenside().
quickplayFinish().
quietMove().
rabarClassification().
rakingBishops().
randomizedChess().
rank().
rapidChess().
recapture().
refute().
relatedSquares().

% A pin where it is legal to move the pinned piece out of the line of attack. Contrast with absolute pin where the pinned piece is not permitted to move because it would expose the king to check.
relativePin(on(piece(Color1,Type1),square(X1,Y1)),on(piece(Color2,Type2),square(X2,Y2)),on(piece(Color2,Type3),square(X3,Y3)),Pos) :-
	pin(on(piece(Color1,Type1),square(X1,Y1)),on(piece(Color2,Type2),square(X2,Y2)),on(piece(Color2,Type3),square(X3,Y3)),Pos),
	Type3 \= king.

remis().
repertoire().
reserveTempo().
resign().
resignOnTime().
romanticChess().
rook().
rookLift().
rookPawn().
roundRobinTournament().
royalFork().
royalPiece().
sac().
sacrifice().
sAN().
sansVoir().
scholarsMate().
score().
scoreSheet().
sealedMove().
second().
secondPlayer().
seesaw().
semiClosedGame().
semiOpenFile().
semiOpenGame().
shamSacrifice().
sharp().
shot().
silentMove().
simplification().
simultaneousChess().
sitzfleisch().
skewer().
skittles().
smotheredMate().
sofiaRules().
solid().
sortie().
sound().
space().
spanishBishop().
speedChess().
spiteCheck().
squeeze().
stalemate().
startingSquare().
stauntonChessSet().
stemGame().
strategicCrush().
strategy().
strong().
strongerSide().
strongpoint().
strongSquare().
suddenDeath().
supportPoint().
swap().
swindle().
swissTournament().
symmetry().
system().
tabia().
tablebase().
tactician().
tactics().
takeback().
tarraschRule().
tD().
technique().
tempo().
tension().
textMove().
thematic().
themeTournament().
theoreticalDraw().
theoreticalNovelty().
threat().
threefoldRepetition().
tiebreaks().
time().
timeControl().
timeDelay().
timePressure().
tN().
topBoard().
touchedPieceRule().
tournament().
tournamentBook().
tournamentDirector().
trade().
transposition().
trap().
trébuchet().
triangulation().
tripledPawns().
troitskyLine().
twoBishops().
undermining().
underpromotion().
unitedStatesChessFederation().
unorthodoxOpening().
unpinning().
unsound().
uSCF().
vacatingSacrifice().
valve().
vanishedCenter().
variant().
variation().
verticalLine().
waitingMove().
wCC().
weakness().
weakSquare().
wFM().
wGM().
white().
white().
wIM().
win().
windmill().
wing().
wingGambit().
winningPercentage().
winningPosition().
womanFideMaster().
womanGrandmaster().
womanInternationalMaster().
wonGame().
wood().
woodpusher().
worldChampion().
wrongColoredBishop().
wrongRookPawn().
xRay().
zeitnot().
zonalTournaments().
zugzwang().
zwischenschach().
zwischenzug().

%% meta-concepts

genlPreds([relativePin,absolutePin],pin).

:- M = concepts, ignore((source_file(M:P,_), functor(P,F,A), M:export(M:F/A), fail)).